#!/bin/bash
# wget https://mls.sk87.top/deb-psql && bash deb-psql
# version by 2025-11-13
# Sergey Krichko
#################

#====================================================================
#------------------------- install POSGRSQL -------------------------
#---Manual Repository Configuration
#---Import the repository key from https://www.postgresql.org/media/keys/ACCC4CF8.asc:
sudo apt install -y curl ca-certificates
sudo install -d /usr/share/postgresql-common/pgdg
sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
 
#---Create /etc/apt/sources.list.d/pgdg.list. The distributions are called codename-pgdg. In the example, replace bookworm with the actual distribution you are using. File contents:
sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
 
#---Finally, update the package lists, and start installing packages:
sudo apt update
sudo apt install -y postgresql-17
