#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# wget --no-check-certificate https://mls.sk87.top/deb-php && bash deb-php 8.5
# version by 2025-11-14
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
. /etc/os-release
if [[ -z "${1:-}" ]]; then
    echo "Ошибка: не указана версия PHP в $0">&2
    exit 1
fi
phpversion=$1
log_info() {
    echo -e "\n==>>==>>==>> Install PHP (https://packages.sury.org/php/) -> $1"
}
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# ==============================================================================================
# ------------------------ Install PHP (https://packages.sury.org/php/) ------------------------
# ----------------------------------------------------------------------------------------------
# 0. [SYSTEM]
log_info ""
log_info "[SYSTEM] -> run update:"
sudo apt update -y
log_info "[SYSTEM] -> [✓ - update completed!]"
# ----------------------------------------------------------------------------------------------
log_info "[SOFT] -> install:"
sudo apt install -y curl ca-certificates apt-transport-https
log_info "[SOFT] -> [✓ - installed!]"
# ----------------------------------------------------------------------------------------------
log_info "add key gpg:"
sudo curl -sSLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb
sudo dpkg -i /tmp/debsuryorg-archive-keyring.deb

log_info "add repository:"
sudo tee /etc/apt/sources.list.d/php.sources > /dev/null <<EOF
Types: deb
URIs: https://packages.sury.org/php/
Suites: ${VERSION_CODENAME}
Architectures: amd64
Components: main
Signed-By: /usr/share/keyrings/debsuryorg-archive-keyring.gpg
EOF
# ----------------------------------------------------------------------------------------------
log_info "update:"
sudo apt update -y

# LXC user uid
if ! getent group php >/dev/null; then
    sudo groupadd -g 234 php
fi
if ! getent passwd php >/dev/null; then
    sudo useradd -u 234 -g 234 --system --no-create-home -s /usr/sbin/nologin php
fi
# ----------------------------------------------------------------------------------------------
log_info "Install PHP"
sudo apt install -y php$phpversion-cli php$phpversion-fpm php$phpversion-common \
 php$phpversion-pgsql php$phpversion-curl php$phpversion-xml \
 php$phpversion-dev php$phpversion-imap php$phpversion-redis php$phpversion-apcu php$phpversion-soap \
 php$phpversion-bcmath php$phpversion-bz2 php$phpversion-opcache  php$phpversion-imagick imagemagick \
 php$phpversion-fpm php$phpversion-gd php$phpversion-gmp php$phpversion-intl php$phpversion-mbstring \
 php$phpversion-xmlrpc php$phpversion-zip php$phpversion-memcache php$phpversion-memcached \
 memcached redis-server
# ----------------------------------------------------------------------------------------------
# ==============================================================================================
log_info "Installed version:" && sudo php -v
sleep 3
echo "==>>==>>==>>============<<==<<==<<=="
sleep 1
echo "==>>==>>==>>    PHP     <<==<<==<<=="
sleep 1
echo "==>>==>>==>> SUCCESSFUL <<==<<==<<=="
sleep 1
echo "==>>==>>==>>============<<==<<==<<=="
sleep 5