#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# https://mls.sk87.top/deb--config-network
# mls-deb--config-network-25-12-13
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
. /etc/os-release
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
if [[ "${DEB_LIB_STATUS:-}" != "loaded" ]]; then
    if source <(wget -qO- https://mls.sk87.top/deb--lib); then
        export DEB_LIB_STATUS="loaded"
        COLOR_SCRIPT=$GREEN
        color_text "$COLOR_SCRIPT" "[✓] deb--lib LOADED"
    else
        echo "ERROR: not loaded deb--lib" >&2
        exit 1
    fi
else
    COLOR_SCRIPT=$GREEN
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# 1. [CONFIG-NETWORK]
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETWORK] ->->-> START Configuration..."

CONFIG_FILE="/etc/network/interfaces"

# Get the name of the active interface
IFACE=$(ip -o -4 route show to default | awk '{print $5}')

# 2. [CONFIG-NETWORK] configuration
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETWORK] ->->-> Interface found: $IFACE"
color_text "$COLOR_SCRIPT" "Select network setup type:"
color_text "$COLOR_SCRIPT" "d) Dynamic (DHCP)"
color_text "$COLOR_SCRIPT" "s) Static IP"
color_text "$COLOR_SCRIPT" "Enter d or s: \c"
read -n 1 -r -s MODE < /dev/tty
# Create backup
cp "$CONFIG_FILE" "$CONFIG_FILE.bak"

if [[ "$MODE" == "d" ]]; then
  color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETWORK] ->->-> DHCP Configuration..."

  cat > "$CONFIG_FILE" <<EOF
auto lo
iface lo inet loopback

auto $IFACE
iface $IFACE inet dhcp
EOF

elif [[ "$MODE" == "s" ]]; then
  color_text "$COLOR_SCRIPT" "Enter a static IP address (e.g. 192.168.1.100): "
  read -p 1 -r -s IP_ADDR < /dev/tty
  color_text "$COLOR_SCRIPT" "Enter a subnet mask (e.g. 255.255.255.0): "
  read -p 1 -r -s NETMASK < /dev/tty
  color_text "$COLOR_SCRIPT" "Enter a gateway (e.g. 192.168.1.1): "
  read -p 1 -r -s GATEWAY < /dev/tty
  color_text "$COLOR_SCRIPT" "Enter a DNS server(s) (e.g. 8.8.8 1.1.1.1): "
  read -p 1 -r -s DNS < /dev/tty

  color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETWORK] ->->-> Setting up a static IP..."

  cat > "$CONFIG_FILE" <<EOF
auto lo
iface lo inet loopback

auto $IFACE
iface $IFACE inet static
  address $IP_ADDR
  netmask $NETMASK
  gateway $GATEWAY
  dns-nameservers $DNS
EOF

else
  color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETWORK][!] ->->-> Without changing network settings. Interruption."
  exit 1
fi

# Reboot network
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETWORK] ->->-> Restarting the interface $IFACE..."
ifdown "$IFACE" && ifup "$IFACE"

# [NETWORK] >>> Network configuration ."
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETWORK][✓] ->->-> Network configuration completed!"