#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
# wget https://mls.sk87.top/deb-psql && bash deb-psql
# version by 2025-11-14
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
set -euo pipefail
. /etc/os-release
if [[ -z "${1:-}" ]]; then
    echo "Ошибка: не указана версия POSTGRESQL в $0">&2
    exit 1
fi
psqlversion=$1
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
#====================================================================
#------------------------- install POSGRSQL -------------------------
#---Manual Repository Configuration
#---Import the repository key from https://www.postgresql.org/media/keys/ACCC4CF8.asc:

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install POSTGRESQL (postgresql repository) ->->-> update && upgrade SYSTEM:"
# 0. [SYSTEM]
echo "==>>==>>==>> [SYSTEM]{$VERSION_CODENAME}->->-> Update and Upgrade"
apt update -y
apt upgrade -y
echo "==>>==>>==>> [SYSTEM][✓] ->->-> update completed!"

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install POSTGRESQL (postgresql repository) ->->-> install soft:"
#---Install the prerequisites:
apt install -y curl ca-certificates gnupg
install -d -m 700 /root/.gnupg

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install POSTGRESQL (postgresql repository) ->->-> add repository:"

install -d /usr/share/postgresql-common/pgdg
curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc -o /tmp/postgresql.asc
gpg --dearmor -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg /tmp/postgresql.asc
rm -f /tmp/postgresql.asc


#---Create /etc/apt/sources.list.d/pgdg.list. The distributions are called codename-pgdg. In the example, replace bookworm with the actual distribution you are using. File contents:
echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg] \
https://apt.postgresql.org/pub/repos/apt $VERSION_CODENAME-pgdg main" \
  > /etc/apt/sources.list.d/pgdg.list

#---Finally, update the package lists, and start installing packages:
apt update
apt install -y postgresql-$psqlversion

echo "==>>==>>==>> Install POSTGRESQL (postgresql repository) ->->-> Installed version:" && psql --version
sleep 3
echo "==>>==>>==>>============<<==<<==<<=="
sleep 2
echo "==>>==>>==>> POSTGRESQL <<==<<==<<=="
sleep 2
echo "==>>==>>==>> SUCCESSFUL <<==<<==<<=="
sleep 2
echo "==>>==>>==>>============<<==<<==<<=="
sleep 4