#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
# wget --no-check-certificate https://mls.sk87.top/deb-psql && bash deb-psql 18
# version by 2025-11-14
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
set -euo pipefail
. /etc/os-release
if [[ -z "${1:-}" ]]; then
    echo "Ошибка: не указана версия POSTGRESQL в $0">&2
    exit 1
fi
psqlversion=$1
log_info() {
    echo -e "\n==>>==>>==>> Install POSTGRESQL (postgresql repository) -> $1"
}
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# ==============================================================================================
# ------------------------- Install POSTGRESQL https://postgresql.org/ -------------------------
# ----------------------------------------------------------------------------------------------
# 0. [SYSTEM]
log_info ""
log_info "[SYSTEM] -> run update:"
sudo apt update -y
log_info "[SYSTEM] -> [✓ - update completed!]"

# ----------------------------------------------------------------------------------------------
log_info "[SOFT] -> install:"
sudo apt install curl ca-certificates
log_info "[SOFT] -> [✓ - installed!]"

# ----------------------------------------------------------------------------------------------
log_info "add key gpg:"
sudo install -d /usr/share/postgresql-common/pgdg
sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc

log_info "add repository:"
sudo tee /etc/apt/sources.list.d/pgdg.sources > /dev/null <<EOF
Types: deb deb-src
URIs: https://apt.postgresql.org/pub/repos/apt
Suites: ${VERSION_CODENAME}-pgdg
Architectures: amd64
Components: main
Signed-By: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
EOF

# ----------------------------------------------------------------------------------------------
log_info "update:"
sudo apt update -y

# LXC user uid
if ! getent group php >/dev/null; then
    sudo groupadd -g 235 postgres
fi
if ! getent passwd php >/dev/null; then
    sudo useradd -u 235 -g 235 -s /bin/bash -d /var/lib/postgresql postgres
fi

log_info "Install POSTGRESQL"
sudo apt install -y postgresql-$psqlversion
# ----------------------------------------------------------------------------------------------
# ==============================================================================================
log_info "Installed version:" && sudo psql --version
sleep 3
echo "==>>==>>==>>============<<==<<==<<=="
sleep 1
echo "==>>==>>==>> POSTGRESQL <<==<<==<<=="
sleep 1
echo "==>>==>>==>> SUCCESSFUL <<==<<==<<=="
sleep 1
echo "==>>==>>==>>============<<==<<==<<=="
sleep 5