#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# wget --no-check-certificate https://mls.sk87.top/deb-stack-LNPP && sudo bash deb-stack-LNPP -ngx -php 8.4 -psql 17
# version by 2025-11-13
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
. /etc/os-release
if [[ $EUID -ne 0 ]]; then
    echo "[!] run is not root [!] Run as root: sudo bash $0" >&2
    exit 1
fi

# Значения по умолчанию
ngxversion=""
phpversion=""
psqlversion=""

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    -ngx)
      ngxversion="$2"
      shift 2
      ;;
    -php)
      phpversion="$2"
      shift 2
      ;;
    -psql)
      psqlversion="$2"
      shift 2
      ;;
    *)
      echo "Ошибка: неизвестный параметр $1"
      echo "Использование: $0 -ngx <версия> -php <версия> -psql <версия>"
      exit 1
      ;;
  esac
done

echo "ngxversion = $ngxversion"
echo "phpversion   = $phpversion"
echo "psqlversion  = $psqlversion"

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

wget --no-check-certificate https://mls.sk87.top/deb-nginx
bash deb-nginx $ngxversion
wait 2

wget --no-check-certificate https://mls.sk87.top/deb-php
bash deb-php $phpversion
wait 2

wget --no-check-certificate https://mls.sk87.top/deb-psql
bash deb-psql $psqlversion
wait 2