#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# https://mls.sk87.top/deb--config-netsoft
# mls-deb--config-netsoft-25-12-13
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
source /etc/os-release
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
if [[ "${DEB_LIB_STATUS:-}" != "loaded" ]]; then
    if source <(curl -sL https://mls.sk87.top/deb--lib); then
        export DEB_LIB_STATUS = "loaded"
        color_text "$CYAN" "[✓] deb--lib LOADED"
    else
        echo "ERROR: not loaded deb--lib" >&2
        exit 1
    fi
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

# 0. [SYSTEM]
color_text "$GREEN" "==>>==>>==>> [SYSTEM] ->->-> Update and Upgrade"
apt update -y && apt upgrade -y
color_text "$GREEN" "==>>==>>==>> [SYSTEM][✓] ->->-> Update and Upgrade completed!"

# 1. [CONFIG-NETSOFT]
color_text "$GREEN" "==>>==>>==>> [CONFIG-NETSOFT] ->->-> Installing network programs..."
install_pkg "mtr"
install_pkg "net-tools"
install_pkg "htop"
color_text "$GREEN" "==>>==>>==>> [CONFIG-NETSOFT][✓] ->->-> Install completed!"