#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# wget --no-check-certificate https://mls.sk87.top/deb-nginx && bash deb-nginx
# version by 2025-11-14
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
. /etc/os-release
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
#===================================================================
#---------------- Install NGINX (nginx repository) -----------------
echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) ->"
# 0. [SYSTEM]
echo "==>>==>>==>> Install NGINX (nginx repository) -> [SYSTEM] -> run update:"
apt update -y
echo "==>>==>>==>> Install NGINX (nginx repository) -> [SYSTEM] -> [✓ - update completed!]"

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) -> [SOFT] -> install:"
#---Install the prerequisites:
sudo apt install curl gnupg2 ca-certificates debian-archive-keyring
gpg --list-keys

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) -> add key gpg:"
curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor \
    | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null

#---Verify that the downloaded file contains the proper key:
gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg

#    The output should contain the full fingerprint 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 as follows:
#    pub   rsa2048 2011-08-19 [SC] [expires: 2027-05-24]
#          573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
#    uid                      nginx signing key <signing-key@nginx.com>
#    Note that the output can contain other keys used to sign the packages. 

#---To set up the apt repository for stable nginx packages, run the following command:
echo "==>>==>>==>> Install NGINX (nginx repository) -> add repository:"
echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] https://nginx.org/packages/debian $VERSION_CODENAME nginx" \
  | sudo tee /etc/apt/sources.list.d/nginx.list

#---Set up repository pinning to prefer our packages over distribution-provided ones:
echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" \
  | sudo tee /etc/apt/preferences.d/99nginx

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) -> update:"
sudo apt update

#---To install -y nginx, run the following commands:
echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) -> Install NGINX LAST STABLE VERSION:"
sudo apt install nginx

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) -> Configure"
#---info about server
#sed -i  '/<h1>Welcome to nginx!</h1>//<h1>Welcome to nginx! </h1>/s  /usr/share/nginx/html/index.html
tee /usr/share/nginx/html/index.html > /dev/null <<EOF
<!DOCTYPE html>
<html>
<head>
<title>$(hostname) nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx! $(hostname)</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
EOF

#---Start NGINX
echo "==>>==>>==>> Install NGINX (nginx repository) ->  Start NGINX"
systemctl start nginx

#---
echo "==>>==>>==>> Install NGINX (nginx repository) -> Installed version:" && nginx -v
sleep 3
echo "==>>==>>==>>============<<==<<==<<=="
sleep 2
echo "==>>==>>==>>   NGINX    <<==<<==<<=="
sleep 2
echo "==>>==>>==>> SUCCESSFUL <<==<<==<<=="
sleep 2
echo "==>>==>>==>>============<<==<<==<<=="
sleep 4