#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# wget --no-check-certificate https://mls.sk87.top/deb-php && bash deb-php 8.5
# version by 2026-06-06
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
. /etc/os-release
if [[ -z "${1:-}" ]]; then
    echo "Ошибка: не указана версия PHP в $0">&2
    exit 1
fi
PHP_VER=$1
log_info() {
    echo -e "\n==>>==>>==>> Install PHP (https://packages.sury.org/php/) -> $1"
}
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# ==============================================================================================
# ------------------------ Install PHP (https://packages.sury.org/php/) ------------------------
# ----------------------------------------------------------------------------------------------
# 0. [SYSTEM]
log_info "[SYSTEM] -> run update:"
sudo apt update -y
log_info "[SYSTEM] -> [✓ - update completed!]"
# ----------------------------------------------------------------------------------------------
log_info "[SOFT] -> install:"
sudo apt install -y curl ca-certificates apt-transport-https
log_info "[SOFT] -> [✓ - installed!]"
# ----------------------------------------------------------------------------------------------
log_info "add key gpg:"
sudo curl -sSLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb
sudo dpkg -i /tmp/debsuryorg-archive-keyring.deb

log_info "add repository:"
sudo tee /etc/apt/sources.list.d/php.sources > /dev/null <<EOF
Types: deb
URIs: https://packages.sury.org/php/
Suites: ${VERSION_CODENAME}
Architectures: amd64
Components: main
Signed-By: /usr/share/keyrings/debsuryorg-archive-keyring.gpg
EOF
# ----------------------------------------------------------------------------------------------
log_info "update:"
sudo apt update -y

# LXC user uid
# if ! getent group php >/dev/null; then
#     sudo groupadd -g 234 php
# fi
# if ! getent passwd php >/dev/null; then
#     sudo useradd -u 234 -g 234 --system --no-create-home -s /usr/sbin/nologin php
# fi
# ----------------------------------------------------------------------------------------------
log_info "Install PHP"
sudo apt install -y php${PHP_VER}-cli php${PHP_VER}-fpm php${PHP_VER}-common
log_info "Install PHP module Required"
sudo apt install -y php${PHP_VER}-curl php${PHP_VER}-xml php${PHP_VER}-gd php${PHP_VER}-mbstring php${PHP_VER}-zip
log_info "Install PHP module Recommended"
sudo apt install -y php${PHP_VER}-apcu redis-server php${PHP_VER}-redis php${PHP_VER}-intl
log_info "Install PHP module For Specific App"
sudo apt install -y php${PHP_VER}-ldap php${PHP_VER}-imap php${PHP_VER}-gmp php${PHP_VER}-imagick php${PHP_VER}-smbclient
sudo apt install -y php${PHP_VER}-pgsql php${PHP_VER}-soap php${PHP_VER}-bcmath php${PHP_VER}-bz2
# ----------------------------------------------------------------------------------------------
# ==============================================================================================
log_info "Installed version:" && sudo php -v
sleep 3
echo "==>>==>>==>>============<<==<<==<<=="
sleep 1
echo "==>>==>>==>>    PHP     <<==<<==<<=="
sleep 1
echo "==>>==>>==>> SUCCESSFUL <<==<<==<<=="
sleep 1
echo "==>>==>>==>>============<<==<<==<<=="
sleep 5