#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# wget https://mls.sk87.top/deb--config-newuser && bash deb--config-newuser
# version by 2025-11-14
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
. /etc/os-release
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

# 0.[SUDO]
echo "==>>==>>==>> [SUDO] ->->-> Installing..."
if ! command -v sudo &> /dev/null; then
    apt install -y sudo
    echo "==>>==>>==>> [SUDO][✓] ->->-> install completed!"
else
    echo "==>>==>>==>> [SUDO][-] ->->-> sudo no installation required"
fi

# 1.[CONFIG-NEWUSER] Checking if the user exists
echo "==>>==>>==>> [CONFIG-NEWUSER] ->->-> create user..."
read -p "Insert name new user: " USERNAME

if id "$USERNAME" &>/dev/null; then
    echo "==>>==>>==>> [CONFIG-NEWUSER] ->->-> User '$USERNAME' already exists."
else
    # === insert password ===
    read -s -p "==>>==>>==>> [CONFIG-NEWUSER] ->->-> Insert password for $USERNAME: " PASSWORD
    echo
    read -s -p "==>>==>>==>> [CONFIG-NEWUSER] ->->-> Repeat password: " PASSWORD2
    echo

    if [ "$PASSWORD" != "$PASSWORD2" ]; then
        echo "==>>==>>==>> [CONFIG-NEWUSER] ->->-> [!] Passwords do not match. Aborting."
        exit 1
    fi

    # === Create user ===
    echo "==>>==>>==>> [CONFIG-NEWUSER] ->->-> Create user $USERNAME..."
    useradd -m -s /bin/bash "$USERNAME"
    echo "$USERNAME:$PASSWORD" | chpasswd
    echo "==>>==>>==>> [CONFIG-NEWUSER] ->->-> User $USERNAME created"

    # === Add group sudo ===
    # usermod -aG sudo "$USERNAME"
    # echo "==>>==>>==>> [CONFIG-NEWUSER] ->->-> User $USERNAME added to sudo group"
fi

# 2.[CONFIG-NEWUSER] Add USERNAME to group sudo ===
usermod -aG sudo "$USERNAME"
echo "==>>==>>==>> [CONFIG-NEWUSER] ->->-> User $USERNAME added to sudo group"