#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# wget --no-check-certificate https://mls.sk87.top/deb-nginx && sudo bash deb-nginx
# version by 2025-11-13
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
. /etc/os-release
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
#===================================================================
#---------------- Install NGINX (nginx repository) -----------------
echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) ->->-> update && upgrade SYSTEM:"
# 0. [SYSTEM]
echo "==>>==>>==>> [SYSTEM]{$VERSION_CODENAME} ->->-> Update and Upgrade"
apt update -y
apt upgrade -y
echo "==>>==>>==>> [SYSTEM][✓] ->->-> update completed!"

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) ->->-> install soft:"
#---Install the prerequisites:
apt install -y curl gnupg ca-certificates debian-archive-keyring 
install -d -m 700 /root/.gnupg

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) ->->-> add repository:"
#---Import an official nginx signing key so apt could verify the packages authenticity. Fetch the key:
curl -fsSL https://nginx.org/keys/nginx_signing.key -o /tmp/nginx.asc
gpg --dearmor -o /usr/share/keyrings/nginx-archive-keyring.gpg /tmp/nginx.asc
rm -f /tmp/nginx.asc

#---Verify that the downloaded file contains the proper key:
gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg

#    The output should contain the full fingerprint 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 as follows:
#    pub   rsa2048 2011-08-19 [SC] [expires: 2027-05-24]
#          573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
#    uid                      nginx signing key <signing-key@nginx.com>
#    Note that the output can contain other keys used to sign the packages. 

#---To set up the apt repository for stable nginx packages, run the following command:
echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian $VERSION_CODENAME nginx" \
  > /etc/apt/sources.list.d/nginx.list

#---Set up repository pinning to prefer our packages over distribution-provided ones:
echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" \
  > /etc/apt/preferences.d/99nginx

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) ->->-> update:"
apt update

#---To install -y nginx, run the following commands:
echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) ->->-> Install NGINX LAST MAIN VERSION:"
apt install -y nginx $1

echo "-----------------------------------------------------"
echo "==>>==>>==>> Install NGINX (nginx repository) ->->-> Configure"

#---create directory
mkdir -p /etc/nginx/{sites-available,sites-enabled}

#---Edit => /etc/nginx/nginx.conf
#---Paste => include /etc/nginx/sites-enabled/*;
sed -i '/include \/etc\/nginx\/conf\.d\/\*\.conf;/a \    include /etc/nginx/sites-enabled/*;' /etc/nginx/nginx.conf
#FIND_LINE='    include /etc/nginx/sites-enabled/*;'
#ADD_LINE='    include /etc/nginx/sites-enabled/*;'
#AFTER_LINE='include /etc/nginx/conf.d/*.conf;'
#FILE='/etc/nginx/nginx.conf'
#if grep -Fxq "$ADD_LINE" "$FILE"; then
#    echo "Настройка уже применена!"
#    else
#    sed -i "/$AFTER_LINE/a $ADD_LINE" "$FILE"
#    echo "Настройка '$ADD_LINE' добавлена."
#fi



#---info about server
#sed -i  '/<h1>Welcome to nginx!</h1>//<h1>Welcome to nginx! </h1>/s  /usr/share/nginx/html/index.html
tee /usr/share/nginx/html/index.html > /dev/null <<EOF
<!DOCTYPE html>
<html>
<head>
<title>$(hostname) nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx! $(hostname)</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
EOF

#---Start NGINX
echo "==>>==>>==>> Install NGINX (nginx repository) ->->-> Start NGINX"
systemctl start nginx

#---
echo "==>>==>>==>> Install NGINX (nginx repository) ->->-> Installed version:"
nginx -v
sleep 3
echo "==>>==>>==>>============<<==<<==<<=="
sleep 2
echo "==>>==>>==>>   NGINX    <<==<<==<<=="
sleep 2
echo "==>>==>>==>> SUCCESSFUL <<==<<==<<=="
sleep 2
echo "==>>==>>==>>============<<==<<==<<=="
sleep 4