#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# https://mls.sk87.top/deb--config-netsoft
# mls-deb--config-netsoft-25-12-13
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
source /etc/os-release
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
if [[ "${DEB_LIB_STATUS:-}" != "loaded" ]]; then
    if source <(wget -qO- https://mls.sk87.top/deb--lib); then
        export DEB_LIB_STATUS="loaded"
        COLOR_SCRIPT=$GREEN
        color_text "$COLOR_SCRIPT" "[✓] deb--lib LOADED"
    else
        echo "ERROR: not loaded deb--lib" >&2
        exit 1
    fi
else
    COLOR_SCRIPT=$GREEN
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

# 1. [CONFIG-NETSOFT]
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETSOFT] ->->-> Installing network programs..."
install_pkg "mtr"
install_pkg "net-tools"
install_pkg "htop"
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETSOFT][✓] ->->-> Install completed!"