#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# wget --no-check-certificate https://mls.sk87.top/deb-stack-LNPP && sudo bash deb-stack-LNPP -ngx 1.28.0-1~trixie -psql 17 -php 8.4 
# version by 2025-11-15
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
. /etc/os-release
if [[ $EUID -ne 0 ]]; then
    echo "[!] run is not root [!] Run as root: sudo bash $0" >&2
    exit 1
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

# Значения по умолчанию
ngxversion=""
psqlversion=""
phpversion=""

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    -ngx)
      ngxversion="$2"
      shift 2
      ;;
    -psql)
      psqlversion="$2"
      shift 2
      ;;
    -php)
      phpversion="$2"
      shift 2
      ;;
    *)
      echo "Ошибка: неизвестный параметр $1"
      echo "Использование: $0 -ngx <версия> -php <версия> -psql <версия>"
      exit 1
      ;;
  esac
done

echo "ngxversion   = $ngxversion"
echo "phpversion   = $phpversion"
echo "psqlversion  = $psqlversion"
sleep 4

wget --no-check-certificate https://mls.sk87.top/deb-nginx
bash deb-nginx $ngxversion
sleep 2

wget --no-check-certificate https://mls.sk87.top/deb-psql
bash deb-psql $psqlversion
sleep 2

wget --no-check-certificate https://mls.sk87.top/deb-php
bash deb-php $phpversion
sleep 2

echo ""
echo "V=V=V=V=V=V=V=V=V=V=V=V=V=V=V=V=V=V=V"
echo ""
sleep 2
echo "==>>==>>==>>============<<==<<==<<=="
sleep 2
echo "==>>==>>==>> STACK LNPP <<==<<==<<=="
sleep 2
echo "==>>==>>==>> SUCCESSFUL <<==<<==<<=="
sleep 2
echo "==>>==>>==>>============<<==<<==<<=="
sleep 4