#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# https://mls.sk87.top/deb--config-newuser
# mls-deb--config-newuser-25-12-13
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
if ! command -v curl >/dev/null 2>&1; then
    apt-get update -qq && apt-get install -y curl >/dev/null
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
if [[ "${DEB_LIB_STATUS:-}" != "loaded" ]]; then
    if source <(curl -sLf https://mls.sk87.top/deb--lib); then
        export DEB_LIB_STATUS="loaded"
        COLOR_SCRIPT=$GREEN
        color_text "$COLOR_SCRIPT" "[✓] deb--lib LOADED"
    else
        echo -e "ERROR: not loaded deb--lib" >&2
        exit 1
    fi
    else
    COLOR_SCRIPT=$GREEN
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
source /etc/os-release
check_update
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#

install_pkg "sudo"

# 1.[CONFIG-NEWUSER] Checking if the user exists
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> create user..."
color_text -n "$COLOR_SCRIPT" "Insert name new user: "
read -p USERNAME < /dev/tty

if id "$USERNAME" &>/dev/null; then
    color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> User '$USERNAME' already exists."
else
    # === insert password ===
    color_text -n "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> Insert password for $USERNAME: "
    read -s -p PASSWORD < /dev/tty
    echo
    color_text -n "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> Repeat password: "
    read -s -p  PASSWORD2 < /dev/tty
    echo

    if [ "$PASSWORD" != "$PASSWORD2" ]; then
        color_text "$RED" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> [!] Passwords do not match. Aborting."
        exit 1
    fi

    # === Create user ===
    color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> Create user $USERNAME..."
    useradd -m -s /bin/bash "$USERNAME"
    echo "$USERNAME:$PASSWORD" | chpasswd
    color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> User $USERNAME created"
fi

# 2.[CONFIG-NEWUSER] Add USERNAME to group sudo ===
usermod -aG sudo "$USERNAME"
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NEWUSER] ->->-> User $USERNAME added to sudo group"