#!/bin/bash
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
# https://mls.sk87.top/deb--config-netsoft
# mls-deb--config-netsoft-25-12-13
# Sergey Krichko
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=# 
set -euo pipefail
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
if ! command -v curl >/dev/null 2>&1; then
    apt-get update -qq && apt-get install -y curl >/dev/null
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
if [[ "${DEB_LIB_STATUS:-}" != "loaded" ]]; then
    if source <(curl -sLf https://mls.sk87.top/deb--lib); then
        export DEB_LIB_STATUS="loaded"
        COLOR_SCRIPT=$GREEN
        color_text "$COLOR_SCRIPT" "[✓] deb--lib LOADED"
    else
        echo -e "ERROR: not loaded deb--lib" >&2
        exit 1
    fi
    else
    COLOR_SCRIPT=$GREEN
fi
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
source /etc/os-release
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
# 1. [CONFIG-NETSOFT]
check_update
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETSOFT] ->->-> Installing network programs..."
install_pkg "mtr"
install_pkg "net-tools"
install_pkg "htop"
color_text "$COLOR_SCRIPT" "==>>==>>==>> [CONFIG-NETSOFT][✓] ->->-> Install completed!"